//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Employee_Id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public int GameDevelopmentCompanyCompany_Id { get; set; }
        public Nullable<int> EmployeeEmployee_Id { get; set; }
        public string Position { get; set; }
    
        public virtual GameDevelopmentCompany GameDevelopmentCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
