//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.BetaVersions = new HashSet<BetaVersion>();
        }
    
        public int Game_Id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public string Release_date { get; set; }
        public int GameDevelopmentCompanyCompany_Id { get; set; }
    
        public virtual GameDevelopmentCompany GameDevelopmentCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetaVersion> BetaVersions { get; set; }
    }
}
