//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDCdbContext : DbContext
    {
        public GDCdbContext()
            : base("name=GDCdbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameDevelopmentCompany> GameDevelopmentCompanies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameBlueprint> GameBlueprints { get; set; }
        public virtual DbSet<Code> Codes { get; set; }
        public virtual DbSet<BetaVersion> BetaVersions { get; set; }
        public virtual DbSet<Art> Arts { get; set; }
    }
}
